INSERT INTO `wedding-table` (`name`, `table_id`, `place_id`) VALUES
('Lucia Lászlóová', '0', '0'),
('Peter Patočka', '0', '1'),
('Marián Patočka', '0', '2'),
('Daniela Patočková', '0', '3'),
('Ján Patočka', '0', '4'),
('Alicka Zvalená', '0', '5'),
('Michal Patočka', '0', '6'),
('Martina', '0', '7'),
('Juraj Jakub Patočka', '0', '8'),
('Ahnesty Ondrak', '0', '9'),
('Reggie Ondrak', '0', '10'),
('Bodhi Ondrak', '0', '11'),
('Kristína Matušeková', '0', '12'),
('Kristína Matušeková +1', '0', '13'),
('Silvia László', '0', '14'),
('Peter László', '0', '15'),
('Ružena Lászlóová', '0', '16'),
('Ľudovít László', '0', '17'),
('Silvia Láslová', '0', '18'),
('Róbert Láslo', '0', '19'),
('Katarína Láslová', '0', '20'),
('Alžbetka Láslová', '0', '21'),
('Anton Patočka', '0', '22'),
('Erika Patočková', '0', '23'),
('Lukáš Patočka', '0', '24'),
('Júlia Masaryková', '0', '25'),
('Jozef Masaryk', '0', '26'),
('Emília Muchová', '0', '27'),
('Sára Patočková', '1', '0'),
('Rebeka Patočková', '1', '1'),
('Adrián Masaryk', '1', '2'),
('Patrícia Masaryková', '1', '3'),
('Linda Masaryková', '1', '4'),
('Terezka Láslová', '1', '5'),
('Emma László', '1', '6'),
('Patrik László', '1', '7'),
('Michal Lančarič', '2', '0'),
('Dana Balonová', '2', '1'),
('Marián Lančarič', '2', '2'),
('Ján Švenk', '2', '3'),
('Henrich Ovcharovich', '2', '4'),
('Patrícia Ovcharovichová', '2', '5'),
('Branislav Gajdoš', '3', '0'),
('Karol Horváth', '3', '1'),
('Lucia Svitákova', '3', '2'),
('Zuzana Kmotríková', '3', '3'),
('Martin Szabo', '3', '4'),
('Eddie Murphy', '3', '5'),
('Ján Zajak', '3', '6'),
('Peter Jacko', '3', '7'),
('Miriam Babalová', '4', '0'),
('Simon', '4', '1'),
('Peter Novák', '4', '2'),
('Ľubomíra Trnavská', '4', '3'),
('Michal Sopko', '4', '4'),
('Evička', '4', '5'),
('Táňa Telekyová', '5', '0'),
('Mikuláš', '5', '1'),
('Stelka', '5', '2'),
('Renáta Hrišová', '5', '3'),
('Renáta Hrišová +1', '5', '4'),
('Daniel Pastorek', '6', '0'),
('Miriam Pastoreková', '6', '1'),
('Zuzana Pastoreková', '6', '2'),
('Lucia Pastoreková', '6', '3'),
('Marek Struhár', '6', '4'),
('Nausheen Struhár', '6', '5'),
('Asher Struhár', '6', '6'),
('Simona Ďurejová', '6', '7'),
('Vlado Ďurej', '6', '8'),
('Semi Ďurej', '6', '9');