version: "2"
services:
  www:
    build: .
    ports:
      - "8001:80"
    volumes:
      - ./api:/var/www/html/api/
    links:
      - db
    networks:
      - default
    environment:
      MYSQL_DATABASE: dbname
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_SERVER: mysql
  db:
    image: mysql
    hostname: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: dbname
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./api/db:/docker-entrypoint-initdb.d
      - persistent:/var/lib/mysql
    networks:
      - default
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - 8000:80
    environment:
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
volumes:
  persistent: